/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.BatchCreateEventsResponse
 * Do not edit manually.
 */

import { Context } from '@model/events/Context';
import { SessionIdResponse } from '@model/events/SessionIdResponse';
import { UserIdResponse } from '@model/events/UserIdResponse';
import { Schema } from '@model/varsapi/Schema';
/**
 * @interface BatchCreateEventsResponse Server response for created events
 */
export interface BatchCreateEventsResponse {
    'user'?: UserIdResponse;
    'session'?: SessionIdResponse;
    'context'?: Context;
    /**
     * The event's name.
     */
    'name': string;
    /**
     * Optional. The event's timestamp represented in ISO 8601 format. If not provided, the current FullStory server time will be used.
     */
    'timestamp'?: string;
    /**
     * Optional. The custom event's payload.
     */
    'properties'?: object;
    'schema'?: Schema;
}

