/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.BrowserContext
 * Do not edit manually.
 */

/**
 * @interface BrowserContext The browser context in which the events are attached to.
 */
export interface BrowserContext {
    'url'?: string;
    'user_agent'?: string;
    'initial_referrer'?: string;
}

