/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.Context
 * Do not edit manually.
 */

import { DeviceContext } from '@model/events/DeviceContext';
import { LocationContext } from '@model/events/LocationContext';
import { MobileContext } from '@model/events/MobileContext';
import { WebContext } from '@model/events/WebContext';

export interface Context {
    'integration'?: string;
    'custom_annotations'?: { [key: string]: string; };
    'web'?: WebContext;
    'mobile'?: MobileContext;
    'device'?: DeviceContext;
    'location'?: LocationContext;
}

