/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.Context
 * Do not edit manually.
 */

import { BrowserContext } from '@model/events/BrowserContext';
import { DeviceContext } from '@model/events/DeviceContext';
import { LocationContext } from '@model/events/LocationContext';
import { MobileContext } from '@model/events/MobileContext';
/**
 * @interface Context The context in which the events are attached to
 */
export interface Context {
    'integration'?: string;
    'custom_annotations'?: { [key: string]: string; };
    'browser'?: BrowserContext;
    'mobile'?: MobileContext;
    'device'?: DeviceContext;
    'location'?: LocationContext;
}

