/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.CreateEventsResponse
 * Do not edit manually.
 */

import { Context } from '@model/events/Context';
import { Event } from '@model/events/Event';
import { SessionResponse } from '@model/events/SessionResponse';
import { UserResponse } from '@model/events/UserResponse';
/**
 * @interface CreateEventsResponse Server response for created events
 */
export interface CreateEventsResponse {
    'user'?: UserResponse;
    'session'?: SessionResponse;
    'context'?: Context;
    'events'?: Array<Event>;
}

