/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.CreateEventsResponseWrapper
 * Do not edit manually.
 */

import { EventData } from '@model/events/EventData';
/**
 * @interface CreateEventsResponseWrapper
 */
export interface CreateEventsResponseWrapper {
    'body'?: EventData;
}

