/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.CreateEventsRequest
 * Do not edit manually.
 */

import { Context } from '@model/events/Context';
import { Event } from '@model/events/Event';
import { SessionIdRequest } from '@model/events/SessionIdRequest';
import { UserIdRequest } from '@model/events/UserIdRequest';

export interface CreateEventsRequest {
    'user'?: UserIdRequest;
    'session'?: SessionIdRequest;
    'context'?: Context;
    'events'?: Array<Event>;
    'include_schema'?: boolean;
}

