/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.DeviceContext
 * Do not edit manually.
 */


export interface DeviceContext {
    'ip'?: string;
    'platform'?: string;
    'os_version'?: string;
    'manufacturer'?: string;
    'model'?: string;
    'serial_number'?: string;
    'features'?: Array<string>;
    'screen_width'?: number;
    'screen_height'?: number;
    'viewport_width'?: number;
    'viewport_height'?: number;
}

