/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.DeviceContext
 * Do not edit manually.
 */

/**
 * @interface DeviceContext The device context in which the events are attached to.
 */
export interface DeviceContext {
    'manufacturer'?: string;
    'model'?: string;
    'screen_width'?: number;
    'screen_height'?: number;
    'viewport_width'?: number;
    'viewport_height'?: number;
}

