/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.EventData
 * Do not edit manually.
 */

import { Context } from '@model/events/Context';
import { SessionId } from '@model/events/SessionId';
import { UserId } from '@model/events/UserId';
import { Schema } from '@model/varsapi/Schema';
/**
 * @interface EventData The event.
 */
export interface EventData {
    'user'?: UserId;
    'session'?: SessionId;
    'context'?: Context;
    /**
     * The event's name.
     */
    'name': string;
    /**
     * Optional. The event's timestamp, defaults to current time.
     */
    'timestamp'?: string;
    /**
     * Optional. The custom event's payload.
     */
    'properties'?: object;
    'schema'?: Schema;
}

