/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.GetBatchEventsImportErrorsResponse.FailedEventsImport
 * Do not edit manually.
 */

import { CreateEventsRequest } from '@model/events/CreateEventsRequest';
/**
 * @interface FailedEventsImport Server response for failed batch events
 */
export interface FailedEventsImport {
    /**
     * Description of the failure encountered while importing the events
     */
    'message'?: string;
    /**
     * Error code
     */
    'code'?: string;
    'events'?: CreateEventsRequest;
}

