/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.GetBatchEventsImportErrorsResponse
 * Do not edit manually.
 */

import { FailedEventsImport } from '@model/events/FailedEventsImport';
/**
 * @interface GetBatchEventsImportErrorsResponse Server response for retrieving batch events import errors
 */
export interface GetBatchEventsImportErrorsResponse {
    /**
     * Page of events import failures for the batch import
     */
    'results'?: Array<FailedEventsImport>;
    /**
     * The total number of failures for the specified events import
     */
    'total_records'?: number;
    /**
     * The token that can be used in a subsequent request to fetch the next page of import failures
     */
    'next_page_token'?: string;
}

