/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.GetBatchEventsImportStatusResponse
 * Do not edit manually.
 */

import { JobMetadata } from '@model/job/JobMetadata';

export interface GetBatchEventsImportStatusResponse {
    /**
    * The stats on the number of events imported successfully
    */
    'imports'?: string;
    /**
    * Only included for failed imports. The stats on the number of events that failed to be imported
    */
    'errors'?: string;
    'job'?: JobMetadata;
}

