/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.GetBatchEventsImportsResponse
 * Do not edit manually.
 */

import { BatchCreateEventsResponse } from '@model/events/BatchCreateEventsResponse';
/**
 * @interface GetBatchEventsImportsResponse Server response for retrieving batch events imported
 */
export interface GetBatchEventsImportsResponse {
    /**
     * Page of events import responses for the batch import
     */
    'results'?: Array<BatchCreateEventsResponse>;
    /**
     * Total number of records in this batch import
     */
    'total_records'?: string;
    /**
     * The token that can be used in a subsequent request to fetch the next page of import results
     */
    'next_page_token'?: string;
}

