/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.LocationContext
 * Do not edit manually.
 */


export interface LocationContext {
    'country_code'?: string;
    'region_code'?: string;
    'city_name'?: string;
    'latitude'?: number;
    'longitude'?: number;
}

