/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.MobileContext
 * Do not edit manually.
 */


export interface MobileContext {
    'app_id'?: string;
    'app_version'?: string;
    'app_name'?: string;
    'build_variant'?: string;
}

