/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.MobileContext
 * Do not edit manually.
 */

/**
 * @interface MobileContext The mobile context in which the events are attached to
 */
export interface MobileContext {
    'app_id'?: string;
    'app_version'?: string;
    'app_name'?: string;
    'build_variant'?: string;
}

