/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.SessionId
 * Do not edit manually.
 */

/**
 * @interface SessionId The session identifier.
 */
export interface SessionId {
    /**
     * The FullStory generated identifier for the session to associate the event with.
     */
    'id'?: string;
    /**
     * Associate events with the most recent session captured from the user, the session much be within the past 30 minutes.
     */
    'use_most_recent'?: boolean;
}

