/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.SessionResponse
 * Do not edit manually.
 */

/**
 * @interface SessionResponse The session identifier
 */
export interface SessionResponse {
    'id'?: string;
}

