/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.SessionIdRequest
 * Do not edit manually.
 */


export interface SessionIdRequest {
    'id'?: string;
    'use_most_recent'?: boolean;
}

