/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.SessionIdRequest
 * Do not edit manually.
 */

/**
 * @interface SessionIdRequest The session identifier
 */
export interface SessionIdRequest {
    /**
     * The FullStory assigned user ID
     */
    'id'?: string;
    /**
     * Use the most recent session for the user
     */
    'use_most_recent'?: boolean;
}

