/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.SessionIdRequest
 * Do not edit manually.
 */

/**
 * @interface SessionIdRequest The session identifier.
 */
export interface SessionIdRequest {
    /**
     * The FullStory generated identifier for the session to associate the event with.
     */
    'id'?: string;
    /**
     * Associate events with the most recent session captured from the user.
     *
     *If set to `true`, a `user` is required. The user must have a session within the past 30 minutes, otherwise the events will be created for the user without a session.
     *
     *It is recommended to use `session.id` instead, when creating events for a specific session.
     */
    'use_most_recent'?: boolean;
}

