/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.SessionIdResponse
 * Do not edit manually.
 */

/**
 * @interface SessionIdResponse The session identifier. If the event is attached to a session.
 */
export interface SessionIdResponse {
    /**
     * The FullStory generated identifier for the session to associate the event with.
     */
    'id'?: string;
}

