/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.UserIdRequest
 * Do not edit manually.
 */

/**
 * @interface UserIdRequest The user identifier.
 *
 *If `session.id` is provided, the `session.id` is enough to identify a session for which to create the event, and `user` will not be accepted.
 *
 *If `session.use_most_recent` is set to `true`, one and only one`user` field is required.
 */
export interface UserIdRequest {
    /**
     * The application-specific ID you've given to the user.
     */
    'uid'?: string;
    /**
     * The FullStory assigned user ID.
     */
    'id'?: string;
}

