/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.UserResponse
 * Do not edit manually.
 */


export interface UserResponse {
    'id'?: string;
    'uid'?: string;
}

