/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.UserId
 * Do not edit manually.
 */

/**
 * @interface UserId The user identifier. Required if `session.use_most_recent` is set to `true` in the request.
 */
export interface UserId {
    /**
     * The application-specific ID you've given to the user
     */
    'uid'?: string;
    /**
     * The FullStory assigned user ID.
     */
    'id'?: string;
}

