/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.UserIdRequest
 * Do not edit manually.
 */

/**
 * @interface UserIdRequest The user identifier. `id` is required if `session` is provided in the request.
 */
export interface UserIdRequest {
    /**
     * The application-specific ID you've given to the user
     */
    'uid'?: string;
    /**
     * The FullStory assigned user ID
     */
    'id'?: string;
}

