/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.events.WebContext
 * Do not edit manually.
 */


export interface WebContext {
    'url'?: string;
    'user_agent'?: string;
    'referrer_url'?: string;
}

