/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.varsapi.Schema
 * Do not edit manually.
 */

/**
 * @interface Schema
 */
export interface Schema {
    /**
     * A mapping of field names to their corresponding types.
     */
    'properties'?: object;
}

