/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.varsapi.Schema
 * Do not edit manually.
 */


export interface Schema {
    /**
    * A mapping of field names to their corresponding types.
    */
    'properties'?: object;
}

