/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.varsapi.TypeConflict
 * Do not edit manually.
 */

/**
 * @interface TypeConflict
 */
export interface TypeConflict {
    /**
     * Any fields that are associated with multiple types.
     */
    'properties'?: object;
}

