/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.job.JobMetadata
 * Do not edit manually.
 */

import { JobStatus } from '@model/job/JobStatus';

/**
* JobMetadata contains metadata about asynchronous jobs.
*/
export class JobMetadata {
    /**
    * ID of the job.
    */
    'id'?: string = undefined;
    'status'?: JobStatus = undefined;
    /**
    * Time the job was accepted.
    */
    'created'?: string = undefined;
    /**
    * Time the job was finished, either successfully or unsuccessfully.
    */
    'finished'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string; }> = [
        {
            'name': 'id',
            'baseName': 'id',
            'type': 'string'
        },
        {
            'name': 'status',
            'baseName': 'status',
            'type': 'JobStatus'
        },
        {
            'name': 'created',
            'baseName': 'created',
            'type': 'string'
        },
        {
            'name': 'finished',
            'baseName': 'finished',
            'type': 'string'
        }
    ];

    static getAttributeTypeMap() {
        return JobMetadata.attributeTypeMap;
    }
}

