/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.job.JobStatusResponse
 * Do not edit manually.
 */

import { JobMetadata } from '@model/job/JobMetadata';
/**
 * @interface JobStatusResponse Server response for the job status
 */
export interface JobStatusResponse {
    /**
     * The stats on the number of items imported successfully
     */
    'imports': number;
    /**
     * Only included for failed imports. The stats on the number of items that failed to be imported
     */
    'errors': number;
    'job': JobMetadata;
}

