/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.CreateBatchUserImportJobResponse
 * Do not edit manually.
 */

import { JobMetadata } from '@model/job/JobMetadata';
/**
 * @interface CreateBatchUserImportJobResponse
 */
export interface CreateBatchUserImportJobResponse {
    'job': JobMetadata;
}

