/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.CreateBatchUserImportJobRequest
 * Do not edit manually.
*/
import { BatchUserImportRequest } from '@model/users/BatchUserImportRequest';
export interface CreateBatchUserImportJobRequest {
    /**
    * The list of users and their information that should be imported in this batch request
    */
    'requests'?: Array<BatchUserImportRequest>;
}

