/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.CreateBatchUserImportJobResponse
 * Do not edit manually.
 */

import { JobMetadata } from '@model/job/JobMetadata';

export class CreateBatchUserImportJobResponse {
    'job'?: JobMetadata = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string; }> = [
        {
            'name': 'job',
            'baseName': 'job',
            'type': 'JobMetadata'
        }
    ];

    static getAttributeTypeMap() {
        return CreateBatchUserImportJobResponse.attributeTypeMap;
    }
}

