/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.CreateUserResponse
 * Do not edit manually.
 */

/**
 * @interface CreateUserResponse Server response for creating a user
 */
export interface CreateUserResponse {
    /**
     * The FullStory assigned user ID
     */
    'id': string;
}

