/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportErrorsResponse.FailedUserImport
 * Do not edit manually.
 */

import { BatchUserImportRequest } from '@model/users/BatchUserImportRequest';
/**
 * @interface FailedUserImport Server response for failed batch users
 */
export interface FailedUserImport {
    /**
     * Description of the failure encountered while importing the user
     */
    'message': string;
    /**
     * Error code
     */
    'code': string;
    'user': BatchUserImportRequest;
}

