/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportStatusResponse
 * Do not edit manually.
 */

import { JobMetadata } from '@model/job/JobMetadata';

export class GetBatchUserImportStatusResponse {
    /**
    * The stats on the number of users imported successfully
    */
    'imports'?: string = undefined;
    /**
    * Only included for failed imports. The stats on the number of users that failed to be imported
    */
    'errors'?: string = undefined;
    'job'?: JobMetadata = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string; }> = [
        {
            'name': 'imports',
            'baseName': 'imports',
            'type': 'string'
        },
        {
            'name': 'errors',
            'baseName': 'errors',
            'type': 'string'
        },
        {
            'name': 'job',
            'baseName': 'job',
            'type': 'JobMetadata'
        }
    ];

    static getAttributeTypeMap() {
        return GetBatchUserImportStatusResponse.attributeTypeMap;
    }
}

