/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportsResponse
 * Do not edit manually.
 */

import { BatchUserImportResponse } from '@model/users/BatchUserImportResponse';

export class GetBatchUserImportsResponse {
    /**
    * Page of user import responses for the batch import
    */
    'results'?: Array<BatchUserImportResponse> = undefined;
    /**
    * Total number of records in this batch import
    */
    'total_records'?: string = undefined;
    /**
    * The token that can be used in a subsequent request to fetch the next page of import results
    */
    'next_page_token'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string; }> = [
        {
            'name': 'results',
            'baseName': 'results',
            'type': 'Array<BatchUserImportResponse>'
        },
        {
            'name': 'total_records',
            'baseName': 'total_records',
            'type': 'string'
        },
        {
            'name': 'next_page_token',
            'baseName': 'next_page_token',
            'type': 'string'
        }
    ];

    static getAttributeTypeMap() {
        return GetBatchUserImportsResponse.attributeTypeMap;
    }
}

