/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportStatusResponse
 * Do not edit manually.
*/
import { JobMetadata } from '@model/job/JobMetadata';
export interface GetBatchUserImportStatusResponse {
    /**
    * The stats on the number of users imported successfully
    */
    'imports'?: string;
    /**
    * Only included for failed imports. The stats on the number of users that failed to be imported
    */
    'errors'?: string;
    'job'?: JobMetadata;
}

