/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportsResponse
 * Do not edit manually.
*/
import { BatchUserImportResponse } from '@model/users/BatchUserImportResponse';
export interface GetBatchUserImportsResponse {
    /**
    * Page of user import responses for the batch import
    */
    'results'?: Array<BatchUserImportResponse>;
    /**
    * Total number of records in this batch import
    */
    'total_records'?: string;
    /**
    * The token that can be used in a subsequent request to fetch the next page of import results
    */
    'next_page_token'?: string;
}

