/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportErrorsResponse
 * Do not edit manually.
 */

import { FailedUserImport } from '@model/users/FailedUserImport';

export class GetBatchUserImportErrorsResponse {
    /**
    * Page of user import failures for the batch import
    */
    'results'?: Array<FailedUserImport> = undefined;
    /**
    * The total number of failures for the specified user import
    */
    'total_records'?: string = undefined;
    /**
    * The token that can be used in a subsequent request to fetch the next page of import failures
    */
    'next_page_token'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string, baseName: string, type: string; }> = [
        {
            'name': 'results',
            'baseName': 'results',
            'type': 'Array<FailedUserImport>'
        },
        {
            'name': 'total_records',
            'baseName': 'total_records',
            'type': 'string'
        },
        {
            'name': 'next_page_token',
            'baseName': 'next_page_token',
            'type': 'string'
        }
    ];

    static getAttributeTypeMap() {
        return GetBatchUserImportErrorsResponse.attributeTypeMap;
    }
}

