/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.GetBatchUserImportErrorsResponse
 * Do not edit manually.
 */

import { FailedUserImport } from '@model/users/FailedUserImport';
/**
 * @interface GetBatchUserImportErrorsResponse Server response for retrieving batch users import errors
 */
export interface GetBatchUserImportErrorsResponse {
    /**
     * Page of user import failures for the batch import
     */
    'results'?: Array<FailedUserImport>;
    /**
     * The total number of failures for the specified user import
     */
    'total_records': number;
    /**
     * The token that can be used in a subsequent request to fetch the next page of import failures
     */
    'next_page_token'?: string;
}

