/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.ListUsersResponse
 * Do not edit manually.
*/
import { GetUserResponse } from '@model/users/GetUserResponse';
export interface ListUsersResponse {
    /**
    * The list of users that match the input filter criteria
    */
    'results'?: Array<GetUserResponse>;
    /**
    * The total number of users that matched the filter criteria
    */
    'total_records'?: string;
    /**
    * The token that can be used in a subsequent request with the same filter criteria to fetch the next page of users
    */
    'next_page_token'?: string;
}

