/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.ListUsersResponse
 * Do not edit manually.
 */

import { GetUserResponse } from '@model/users/GetUserResponse';

export class ListUsersResponse {
    /**
    * The list of users that match the input filter criteria
    */
    'results'?: Array<GetUserResponse> = undefined;
    /**
    * The total number of users that matched the filter criteria
    */
    'total_records'?: string = undefined;
    /**
    * The token that can be used in a subsequent request with the same filter criteria to fetch the next page of users
    */
    'next_page_token'?: string = undefined;
}

