/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.ListUsersResponse
 * Do not edit manually.
 */

import { GetUserResponse } from '@model/users/GetUserResponse';
/**
 * @interface ListUsersResponse Server response for listing all users satisfying the request
 */
export interface ListUsersResponse {
    /**
     * The list of users that match the input filter criteria
     */
    'results': Array<GetUserResponse>;
    /**
     * The total number of users that matched the filter criteria
     */
    'total_records': number;
    /**
     * The token that can be used in a subsequent request with the same filter criteria to fetch the next page of users
     */
    'next_page_token': string;
    /**
     * A link to an anonymous segment in the FullStory app contining these users.
     */
    'app_url'?: string;
}

