/* eslint multiline-comment-style: ["error", "starred-block"] */
/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Generated from schema: fullstory.v2.users.UpdateUserResponse
 * Do not edit manually.
 */

/**
 * @interface UpdateUserResponse Server response payload for updating a user
 */
export interface UpdateUserResponse {
    /**
     * The FullStory assigned user ID
     */
    'id': string;
}

