/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class ApierrorErrorResponse {
    /**
    * Long form description of what went wrong
    */
    'message'?: string = undefined;
    /**
    * A short snake-cased value that is safe to handle programmatically
    */
    'code'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApierrorErrorResponse.attributeTypeMap;
    }
}

