/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsUserIdRequest {
    /**
    * The application-specific ID you\'ve given to the user
    */
    'uid'?: string = undefined;
    /**
    * The FullStory assigned user ID
    */
    'id'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EventsUserIdRequest.attributeTypeMap;
    }
}

