/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsEvent {
    /**
    * The event name.
    */
    'name'?: string = undefined;
    /**
    * Optional event timestamp, defaults to current time.
    */
    'timestamp'?: string = undefined;
    /**
    * The custom event payload.
    */
    'properties'?: object = undefined;
    'schema'?: V2eventsSchema = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "object"
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "V2eventsSchema"
        }    ];

    static getAttributeTypeMap() {
        return EventsEvent.attributeTypeMap;
    }
}

