/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsDeviceContext {
    'ip'?: string = undefined;
    'platform'?: string = undefined;
    'os_version'?: string = undefined;
    'manufacturer'?: string = undefined;
    'model'?: string = undefined;
    'serial_number'?: string = undefined;
    'features'?: Array<string> = undefined;
    'screen_width'?: number = undefined;
    'screen_height'?: number = undefined;
    'viewport_width'?: number = undefined;
    'viewport_height'?: number = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "os_version",
            "baseName": "os_version",
            "type": "string"
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "serial_number",
            "baseName": "serial_number",
            "type": "string"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<string>"
        },
        {
            "name": "screen_width",
            "baseName": "screen_width",
            "type": "number"
        },
        {
            "name": "screen_height",
            "baseName": "screen_height",
            "type": "number"
        },
        {
            "name": "viewport_width",
            "baseName": "viewport_width",
            "type": "number"
        },
        {
            "name": "viewport_height",
            "baseName": "viewport_height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return EventsDeviceContext.attributeTypeMap;
    }
}

