/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsCreateEventsRequest {
    'user'?: EventsUserIdRequest = undefined;
    'session'?: EventsSessionIdRequest = undefined;
    'context'?: EventsContext = undefined;
    'events'?: Array<EventsEvent> = undefined;
    'include_schema'?: boolean = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "EventsUserIdRequest"
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "EventsSessionIdRequest"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "EventsContext"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<EventsEvent>"
        },
        {
            "name": "include_schema",
            "baseName": "include_schema",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EventsCreateEventsRequest.attributeTypeMap;
    }
}

