/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsCreateBatchEventsImportJobRequest {
    /**
    * The list of event requests that should be imported
    */
    'requests'?: Array<EventsCreateEventsRequest> = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requests",
            "baseName": "requests",
            "type": "Array<EventsCreateEventsRequest>"
        }    ];

    static getAttributeTypeMap() {
        return EventsCreateBatchEventsImportJobRequest.attributeTypeMap;
    }
}

