/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsContext {
    'integration'?: string = undefined;
    'custom_annotations'?: { [key: string]: string; } = undefined;
    'web'?: EventsWebContext = undefined;
    'mobile'?: EventsMobileContext = undefined;
    'device'?: EventsDeviceContext = undefined;
    'location'?: EventsLocationContext = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "integration",
            "baseName": "integration",
            "type": "string"
        },
        {
            "name": "custom_annotations",
            "baseName": "custom_annotations",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "web",
            "baseName": "web",
            "type": "EventsWebContext"
        },
        {
            "name": "mobile",
            "baseName": "mobile",
            "type": "EventsMobileContext"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "EventsDeviceContext"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "EventsLocationContext"
        }    ];

    static getAttributeTypeMap() {
        return EventsContext.attributeTypeMap;
    }
}

