/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsWebContext {
    'url'?: string = undefined;
    'user_agent'?: string = undefined;
    'referrer_url'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "user_agent",
            "baseName": "user_agent",
            "type": "string"
        },
        {
            "name": "referrer_url",
            "baseName": "referrer_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EventsWebContext.attributeTypeMap;
    }
}

