/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsSessionIdRequest {
    'session_id'?: string = undefined;
    'use_most_recent'?: boolean = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "session_id",
            "baseName": "session_id",
            "type": "string"
        },
        {
            "name": "use_most_recent",
            "baseName": "use_most_recent",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EventsSessionIdRequest.attributeTypeMap;
    }
}

