/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class EventsMobileContext {
    'app_id'?: string = undefined;
    'app_version'?: string = undefined;
    'app_name'?: string = undefined;
    'build_variant'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app_id",
            "baseName": "app_id",
            "type": "string"
        },
        {
            "name": "app_version",
            "baseName": "app_version",
            "type": "string"
        },
        {
            "name": "app_name",
            "baseName": "app_name",
            "type": "string"
        },
        {
            "name": "build_variant",
            "baseName": "build_variant",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EventsMobileContext.attributeTypeMap;
    }
}

