/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class GetBatchEventsImportErrorsResponseFailedEventsImport {
    /**
    * Description of the failure encountered while importing the events
    */
    'message'?: string = undefined;
    /**
    * Error code
    */
    'code'?: string = undefined;
    'events'?: EventsCreateEventsRequest = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "EventsCreateEventsRequest"
        }    ];

    static getAttributeTypeMap() {
        return GetBatchEventsImportErrorsResponseFailedEventsImport.attributeTypeMap;
    }
}

