/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class GetBatchUserImportErrorsResponseFailedUserImport {
    /**
    * Description of the failure encountered while importing the user
    */
    'message'?: string = undefined;
    /**
    * Error code
    */
    'code'?: string = undefined;
    'user'?: UsersBatchUserImportRequest = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UsersBatchUserImportRequest"
        }    ];

    static getAttributeTypeMap() {
        return GetBatchUserImportErrorsResponseFailedUserImport.attributeTypeMap;
    }
}

