/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


/**
* JobMetadata contains metadata about asynchronous jobs.
*/
export class JobJobMetadata {
    /**
    * ID of the job.
    */
    'id'?: string = undefined;
    'status'?: JobJobStatus = undefined;
    /**
    * Time the job was accepted.
    */
    'created'?: string = undefined;
    /**
    * Time the job was finished, either successfully or unsuccessfully.
    */
    'finished'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JobJobStatus"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string"
        },
        {
            "name": "finished",
            "baseName": "finished",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return JobJobMetadata.attributeTypeMap;
    }
}

export namespace JobJobMetadata {
}
