/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


/**
*  - UNKNOWN: Indicates that the field is yet to be populated. It is invalid for the status of a job to actually be UNKNOWN.  - PROCESSING: Indicates that the job has been accepted by FullStory and is being processed.  - COMPLETED: Indicates that the job has been completed successfully without any errors.  - FAILED: Indicates that the job has failures, including partial failures.
*/
export enum JobJobStatus {
    Unknown = <any> 'UNKNOWN',
    Processing = <any> 'PROCESSING',
    Completed = <any> 'COMPLETED',
    Failed = <any> 'FAILED'
}
