/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class UsersListUsersResponse {
    /**
    * The list of users that match the input filter criteria
    */
    'results'?: Array<UsersGetUserResponse> = undefined;
    /**
    * The total number of users that matched the filter criteria
    */
    'total_records'?: string = undefined;
    /**
    * The token that can be used in a subsequent request with the same filter criteria to fetch the next page of users
    */
    'next_page_token'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<UsersGetUserResponse>"
        },
        {
            "name": "total_records",
            "baseName": "total_records",
            "type": "string"
        },
        {
            "name": "next_page_token",
            "baseName": "next_page_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UsersListUsersResponse.attributeTypeMap;
    }
}

