/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class UsersGetBatchUserImportsResponse {
    /**
    * Page of user import responses for the batch import
    */
    'results'?: Array<UsersBatchUserImportResponse> = undefined;
    /**
    * Total number of records in this batch import
    */
    'total_records'?: string = undefined;
    /**
    * The token that can be used in a subsequent request to fetch the next page of import results
    */
    'next_page_token'?: string = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<UsersBatchUserImportResponse>"
        },
        {
            "name": "total_records",
            "baseName": "total_records",
            "type": "string"
        },
        {
            "name": "next_page_token",
            "baseName": "next_page_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UsersGetBatchUserImportsResponse.attributeTypeMap;
    }
}

