/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class UsersCreateBatchUserImportJobResponse {
    'job'?: JobJobMetadata = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "job",
            "baseName": "job",
            "type": "JobJobMetadata"
        }    ];

    static getAttributeTypeMap() {
        return UsersCreateBatchUserImportJobResponse.attributeTypeMap;
    }
}

