/**
 * This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit manually.
 */


export class V2eventsSchema {
    /**
    * A mapping of field names to their corresponding types.
    */
    'properties'?: object = undefined;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return V2eventsSchema.attributeTypeMap;
    }
}

