# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  maven: circleci/maven@1.3

jobs:
  build-pack:
    executor: node/default
    steps:
      - checkout
      - node/install
      - node/install-packages
      # - run:
      #     name: "set-up-smoke-test-env"
      #     command: |
      #       echo "RUN_SMOKE_TESTS=true" >> .env
      #       echo "FS_API_KEY=${ECO_API_KEY}" >> .env
      - run:
          name: "npm-test"
          command: npm run test
      - run:
          name: "npm-build"
          command: npm run build:production
      - run:
          name: "npm-pack"
          command: npm pack
      - run:
          name: "check folder"
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            pwd
      - persist_to_workspace:
          root: .
          paths: 
            - .
  deploy-npm:
      executor: node/default
      steps:
        - attach_workspace:
            at: .
        - run:
            name: "check folder"
            command: |
              echo $CIRCLE_WORKING_DIRECTORY
              pwd
              ls .
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
        - run:
            name: Publish package
            command: npm publish --dry-run

workflows:
  run-tests:
    jobs:
      - node/run:
          name: "Run lint"
          npm-run: lint
      - node/test:
          matrix:
            parameters:
              version: ["14.21.3","16.19.1","18.15.0"]
          pkg-manager: npm
          test-results-for: jest
      - node/run:
          name: "Run Build"
          npm-run: build
      - node/run:
          name: "Run Build Production"
          npm-run: build:production
      - maven/test:
          name: "Run maven test"
          app_src_directory: openapi-generator
          test_results_path: openapi-generator/target/surefire-reports
  hold-and-deploy:
    # when:
      # and:
        # - matches: { pattern: /^v.*/, value: << pipeline.git.tag >> }
    jobs:
      - build-pack
      - hold:
          type: approval
          requires:
            - build-pack
      - deploy-npm:
          requires:
            - hold
