# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  maven: circleci/maven@1.3




# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - node/test:
          version: '16.17'
          pkg-manager: npm
          test-results-for: jest
          test-results-path: test-results/junit.xml
      - maven/test:
          app_src_directory: openapi-generator
          test_results_path: test-results/openapi-generator.xml
      - store_test_results:
          path: test-results/openapi-generator.xml
          require: node/test
      - store_test_results:
          path: test-results/junit.xml
          require: maven/test
