# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  maven: circleci/maven@1.3

jobs:
  build-pack:
    executor: node/default
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: "set-up-smoke-test-env"
          command: |
            echo "RUN_SMOKE_TESTS=true" >> .env
            echo "FS_API_KEY=${ECO_API_KEY}" >> .env
      - run:
          name: "npm-test"
          command: npm run test
      - run:
          name: "npm-build"
          command: npm run build:production
      - run:
          name: "npm-pack"
          command: npm pack
      # persist current folder for checkout and artifacts
      - persist_to_workspace:
          root: .
          paths: 
            - .
  deploy-npm:
      executor: node/default
      steps:
        # restore from build-pack job
        - attach_workspace:
            at: .
        - run:
            name: authenticate-with-registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
        - run:
            name: publish-package
            command: npm publish --access public

workflows:
  run-tests:
    jobs:
      - node/run:
          name: "run-lint"
          npm-run: lint
      - node/test:
          matrix:
            parameters:
              version: ["14.21.3","16.19.1","18.15.0"]
          pkg-manager: npm
          test-results-for: jest
      - node/run:
          name: "run-build"
          npm-run: build
      - node/run:
          name: "run-build-production"
          npm-run: build:production
      - maven/test:
          name: "run-maven-test"
          app_src_directory: openapi-generator
          test_results_path: openapi-generator/target/surefire-reports
  hold-and-deploy:
    when:
      and:
        # only run when a new version is tagged
        - matches: { pattern: /^v.*/, value: << pipeline.git.tag >> }
    jobs:
      - build-pack
      - hold:
          type: approval
          requires:
            - build-pack
      - deploy-npm:
          requires:
            - hold
