# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  maven: circleci/maven@1.3

jobs:
  build-pack:
    executor: node/default
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: "set-up-smoke-test-env"
          command: |
            echo "RUN_SMOKE_TESTS=true" >> .env
            echo "FS_API_KEY=${ECO_API_KEY}" >> .env
      - run:
          name: "npm-test"
          command: npm run test
      - run:
          name: "npm-build"
          command: npm run build:production
      - run:
          name: "npm-pack"
          command: npm pack
      - run:
          name: "set-npm-version" 
          command: |
            echo "export NPM_PACKAGE_VERSION=$(npm pkg get version)" >> $BASH_ENV
      - run: 
          name: "set-is-beta"
          command: |
            if [[ $NPM_PACKAGE_VERSION == *"beta"* ]];
            then
              echo "export IS_BETA=true" >> $BASH_ENV
            else
              echo "export IS_BETA=false" >> $BASH_ENV
            fi
      - run:
          name: "export-env"
          command: |
            echo "Will publish version: $NPM_PACKAGE_VERSION, is beta: $IS_BETA"
            cp $BASH_ENV bash.env
      # persist current folder including env for the deploy-npm job
      - persist_to_workspace:
          root: .
          paths: 
            - .
  deploy-npm:
      executor: node/default
      steps:
        # restore from build-pack job
        - attach_workspace:
            at: .
        - run: 
            name: "restore-bash-env"
            command: cat bash.env >> $BASH_ENV
        - run:
            name: authenticate-with-registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
        - run:
            name: publish-package
            command: |
              if [ $IS_BETA == "true" ];
              then
                npm publish --access public --tag beta latest
              else
                npm publish --access public --tag latest
              fi

workflows:
  run-tests:
    jobs:
      - node/run:
          name: "run-lint"
          npm-run: lint
      - node/test:
          matrix:
            parameters:
              version: ["14.21.3","16.19.1","18.15.0"]
          pkg-manager: npm
          test-results-for: jest
      - node/run:
          name: "run-build"
          npm-run: build
      - node/run:
          name: "run-build-production"
          npm-run: build:production
      - maven/test:
          name: "run-maven-test"
          app_src_directory: openapi-generator
          test_results_path: openapi-generator/target/surefire-reports
  hold-and-deploy:
    jobs:
      - build-pack:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - build-pack
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-npm:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
